/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2019-01-06

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics


CS   : GPIO PortA 4
SCK  : GPIO PortA 5
MISO : GPIO PortA 6
MOSI : GPIO PortA 7
RST  : GPIO PortA 3

******************************************************************************
*/

/* Includes */
#include <stdio.h>
#include <stddef.h>
#include "stm32f10x.h"
#include "mcu_handler.h"
#include "w5500_init.h"

/* Private typedef */
/* Private define  */

/* Private macro */
/* Private variables */
 USART_InitTypeDef USART_InitStructure;

/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  /* TODO - Add your application code here */
	RCC_Configuration();
	USART1_Configuration();
	W5500_SPI_Init();

	W5500_Init();
	Net_Conf();
	Net_Conn();

  /* Infinite loop */
  while (1)
  {

  }
}
